# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c8d7bfc9726a99b657890f55f8ce6da2f850e48ae752ec16c6389d69395e9cb5cdf5740700ca5756b16156c8652acb13752954c6aeb3d2afd4f6ae1bb5ab5af

test:
  secret_key_base: d197470fb832926ec0c72e30b904af1ba639bc55ec9e36034fbd766bba181675d5aab2a0d5dc9fdd340360cd017d59fe30903e8f6904231d2612a39bb84733d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
